# Generated by Django 4.0.3 on 2022-03-28 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_scraperdata_analyticalvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperdata',
            name='code',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyticalvalue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 20, 27, 33, 847193)),
        ),
    ]
